Flag for camera info publishing.
clearpathrobotics/pointgrey_camera_driver pull request #8
Opened 2017-06-12 19:42 UTC by v-mehta

Added flag to enable/disable camera info publishing and required publisher for image transport.

This is needed so we can use other sources of camera calibration parameters like Kalibr.

2017-06-12 20:01 UTC, servos requested changes

2017-06-12 20:01 UTC, servos commented on pointgrey_camera_driver/src/nodelet.cpp
>      it_pub_ = it_->advertiseCamera("image_raw", 5, cb, cb);
should probably only construct one of these publishers based on the param.

2017-06-12 20:03 UTC, v-mehta commented on pointgrey_camera_driver/src/nodelet.cpp
>      it_pub_ = it_->advertiseCamera("image_raw", 5, cb, cb);
Good point! Will update and ping again for review.

2017-06-12 22:52 UTC, efernandez approved these changes
Minor comments only.

2017-06-12 22:52 UTC, efernandez commented on pointgrey_camera_driver/src/nodelet.cpp
> +
remove empty line

2017-06-12 22:52 UTC, efernandez commented on pointgrey_camera_driver/src/nodelet.cpp
> +            if(publish_camera_info_)
It'd be cleaner to have a functor or function that you call like this: `publish(wfov_image->image);`

That function can be set on the constructor depending on the `publish_camera_info_` param.

2017-06-13 15:57 UTC, servos approved these changes

2017-06-13 16:35 UTC, efernandez approved these changes
Only a minor change remains, but consider if optional if you want.

2017-06-14 20:46 UTC, efernandez commented
@v-mehta merge?

---
Side note: @asaini89 I can list other users here, I think the problem you're seeing are b/c new forked repos don't have contributions from us.

2017-06-14 20:49 UTC, merged